use numpy::PyReadonlyArray2;
use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;

use super::fault::Fault;
use super::lift::LiftedFault;

/// A single pass through the array: which activation rows and output rows
/// are connected, and where they land in the array.
///
/// `activation_rows`/`output_rows` are `(start, end)`, a half-open range.
// NOTE: PyO3 0.29 has no `FromPyObject`/`IntoPyObject` for `Range`, so
// tuples stand in here, same as `AccumulatorFaultPart.for_activations`. See
// `systolic::Pass`'s doc comment for what a pass means.
#[pyclass(eq, from_py_object, name = "Pass")]
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Pass {
    #[pyo3(get)]
    pub activation_rows: (usize, usize),
    #[pyo3(get)]
    pub output_rows: (usize, usize),
    #[pyo3(get)]
    pub array_row_start: usize,
    #[pyo3(get)]
    pub array_col_start: usize,
}

#[pymethods]
impl Pass {
    #[new]
    #[pyo3(signature = (activation_rows, output_rows, array_row_start=0, array_col_start=0))]
    fn new(
        activation_rows: (usize, usize),
        output_rows: (usize, usize),
        array_row_start: usize,
        array_col_start: usize,
    ) -> Self {
        Self {
            activation_rows,
            output_rows,
            array_row_start,
            array_col_start,
        }
    }
}

impl From<Pass> for systolic::Pass {
    fn from(value: Pass) -> Self {
        systolic::Pass {
            array_row_start: value.array_row_start,
            activation_rows: value.activation_rows.0..value.activation_rows.1,
            array_col_start: value.array_col_start,
            output_rows: value.output_rows.0..value.output_rows.1,
        }
    }
}

/// How a matrix multiplication is mapped onto a systolic array, as an
/// ordered series of passes. Also the entry point for lifting a register
/// fault to matrix space (see `lift`).
#[pyclass(skip_from_py_object, name = "Mapping")]
#[derive(Debug, Clone)]
pub struct Mapping(pub systolic::Mapping);

#[pymethods]
impl Mapping {
    /// Build a mapping from explicit passes.
    ///
    /// Raises `ValueError` if `passes` is empty. Call `validate()` afterwards
    /// if `passes` wasn't generated by a known-correct algorithm; here only the
    /// empty case is rejected.
    #[staticmethod]
    fn new(passes: Vec<Pass>) -> PyResult<Self> {
        systolic::Mapping::new_checked(passes.into_iter().map(systolic::Pass::from))
            .map(Self)
            .ok_or_else(|| PyValueError::new_err("a mapping needs at least one pass"))
    }

    /// Automatically map `weights` (`out_features, in_features`) onto an
    /// `array_nrows x array_ncols` array, splitting into multiple passes if
    /// the weights don't fit in one.
    #[staticmethod]
    fn auto_for(weights: PyReadonlyArray2<f32>, array_nrows: usize, array_ncols: usize) -> Self {
        let weights = weights.as_array();
        Self(systolic::Mapping::auto_for(
            &weights,
            array_nrows,
            array_ncols,
        ))
    }

    /// Check that every input row is connected to every output row exactly
    /// once and that row-to-array-index assignments are consistent across
    /// passes.
    ///
    /// Raises `ValueError` with the specific problem if not.
    fn validate(&self) -> PyResult<()> {
        self.0
            .validate()
            .map_err(|error| PyValueError::new_err(error.to_string()))
    }

    /// Lift a register fault targeting this mapping's array to matrix
    /// space. The result describes an equivalent operation on the
    /// weight/activation/output matrices rather than the array's physical
    /// registers.
    fn lift(&self, fault: &Fault) -> LiftedFault {
        let targeted = fault.to_targeted();
        self.0.lift_register_fault(&targeted).data.into()
    }
}
