[project]
name = "hamming-utils"
version = "0.1.0"
description = "Error correction utilities for pytorch"
authors = [
    { name = "Marten Roots", email = "rezzubs@proton.me" }
]
requires-python = ">=3.11"
dependencies = [
    "hamming-core",
    "matplotlib>=3.10.5",
    "numpy>=2.3.1",
    "torch>=2.7.1",
]

[dependency-groups]
dev = [
    "pyright>=1.1.403",
    "ruff>=0.12.4",
    "torchvision>=0.22.1",
]

[tool.uv.sources]
hamming-core = { workspace = true }

[tool.uv.workspace]
members = ["hamming-core"]

[build-system]
requires = ["uv_build>=0.7.21,<0.8"]
build-backend = "uv_build"
