[project]
name = "hamming_utils"
version = "0.1.0"
description = "Utilities for protecting pytorch modules with hamming codes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hamming_core",
    "matplotlib>=3.10.5",
    "numpy>=2.3.1",
    "torch>=2.7.1",
]

[dependency-groups]
dev = [
    "pyright>=1.1.403",
    "ruff>=0.12.4",
    "torchvision>=0.22.1",
]

[tool.uv]
cache-keys = [{file = "pyproject.toml"}, {file = "./hamming_core/Cargo.toml"}, {file = "**/*.rs"}]

[tool.uv.sources]
hamming_core = { workspace = true }

[tool.uv.workspace]
members = ["hamming_core/", "."]

[tool.setuptools]
py-modules = ["hamming_utils"]

