[project]
name = "pytorch-ecc"
version = "0.1.0"
description = "Error correction utilities for pytorch"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hamming",
    "numpy>=2.3.1",
    "torch>=2.7.1",
]

[dependency-groups]
dev = [
    "pyright>=1.1.403",
    "ruff>=0.12.4",
    "torchvision>=0.22.1",
]

[tool.uv]
cache-keys = [{file = "pyproject.toml"}, {file = "./hamming/Cargo.toml"}, {file = "**/*.rs"}]

[tool.uv.sources]
hamming = { workspace = true }

[tool.uv.workspace]
members = ["hamming/", "."]

[tool.setuptools]
py-modules = ["pytorch_ecc"]

