import numpy as np
import numpy.typing as npt

def encode_f32(arr: npt.NDArray[np.float32]) -> None: ...
def decode_f32(arr: npt.NDArray[np.float32]) -> None: ...
def encode_u16(arr: npt.NDArray[np.uint16]) -> None: ...
def decode_u16(arr: npt.NDArray[np.uint16]) -> None: ...
